name: "rezervo-web"
services:
  rezervo-web:
    container_name: rezervo-web
    build:
      dockerfile: ./Dockerfile
      args:
        VITE_CONFIG_HOST: ${VITE_CONFIG_HOST}
    restart: unless-stopped
    ports:
      - 3000:3000
    env_file:
      - .env.local
    extra_hosts:
      - "host.docker.internal:host-gateway"
