/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/chains": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chains */
        get: operations["get_chains_chains_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chains/{chain_identifier}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chain By Identifier */
        get: operations["get_chain_by_identifier_chains__chain_identifier__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/schedule/{chain_identifier}/{compact_iso_week}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chain Week Schedule */
        get: operations["get_chain_week_schedule_schedule__chain_identifier___compact_iso_week__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{chain_identifier}/{class_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chain Class By Id */
        get: operations["get_chain_class_by_id_classes__chain_identifier___class_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Activity Categories */
        get: operations["get_activity_categories_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{chain_identifier}/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chain User Profile */
        get: operations["get_chain_user_profile__chain_identifier__user_get"];
        /** Put Chain User Creds */
        put: operations["put_chain_user_creds__chain_identifier__user_put"];
        post?: never;
        /** Delete Chain User */
        delete: operations["delete_chain_user__chain_identifier__user_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{chain_identifier}/user/totp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Chain User Totp */
        put: operations["put_chain_user_totp__chain_identifier__user_totp_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{chain_identifier}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chain Config */
        get: operations["get_chain_config__chain_identifier__config_get"];
        /** Put Chain Config */
        put: operations["put_chain_config__chain_identifier__config_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{chain_identifier}/all-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Configs Index */
        get: operations["get_all_configs_index__chain_identifier__all_configs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Preferences */
        get: operations["get_user_preferences_preferences_get"];
        /** Upsert User Preferences */
        put: operations["upsert_user_preferences_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/features": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Features */
        get: operations["get_features_features_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{chain_identifier}/book": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Book Class Api */
        post: operations["book_class_api__chain_identifier__book_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{chain_identifier}/cancel-booking": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel Booking Api */
        post: operations["cancel_booking_api__chain_identifier__cancel_booking_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{chain_identifier}/sessions-index": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Sessions Index */
        get: operations["get_sessions_index__chain_identifier__sessions_index_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cal-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calendar Token */
        get: operations["get_calendar_token_cal_token_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calendar */
        get: operations["get_calendar_cal_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/push/public-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Push Notifications Public Key */
        get: operations["get_push_notifications_public_key_notifications_push_public_key_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Subscribe To Push Notifications */
        put: operations["subscribe_to_push_notifications_notifications_push_put"];
        post?: never;
        /** Unsubscribe From Push Notifications */
        delete: operations["unsubscribe_from_push_notifications_notifications_push_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/notifications/push/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Push Notifications Subscription */
        post: operations["verify_push_notifications_subscription_notifications_push_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/slackinteraction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Slack Action */
        post: operations["slack_action_slackinteraction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert User */
        put: operations["upsert_user_user_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Sessions */
        get: operations["get_user_sessions_user_sessions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/chain-configs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Chain Configs */
        get: operations["get_user_chain_configs_user_chain_configs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/avatar/{size_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Avatar */
        get: operations["get_user_avatar_user_me_avatar__size_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/{user_id}/avatar/{size_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Avatar By Id */
        get: operations["get_user_avatar_by_id_user__user_id__avatar__size_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upsert User Avatar */
        put: operations["upsert_user_avatar_user_me_avatar_put"];
        post?: never;
        /** Delete User Avatar */
        delete: operations["delete_user_avatar_user_me_avatar_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Community */
        get: operations["get_community_community_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/community/relationship": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update Relationship */
        put: operations["update_relationship_community_relationship_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/webhooks/user-lifecycle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** User Lifecycle */
        post: operations["user_lifecycle_webhooks_user_lifecycle_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/{chain_identifier}/check-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Check In */
        post: operations["check_in__chain_identifier__check_in_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AllowedTimeWindowConfig */
        AllowedTimeWindowConfig: {
            notBefore: components["schemas"]["HourAndMinute"];
            notAfter: components["schemas"]["HourAndMinute"];
        };
        /** BaseChainConfig */
        BaseChainConfig: {
            /** Recurringbookings */
            recurringBookings: components["schemas"]["Class"][];
            /**
             * Active
             * @default true
             */
            active: boolean;
        };
        /** BaseLocation */
        BaseLocation: {
            identifier: components["schemas"]["LocationIdentifier"];
            /** Name */
            name: string;
            /**
             * Checkinterminals
             * @default []
             */
            checkInTerminals: components["schemas"]["CheckInTerminal"][] | null;
        };
        /** BaseUserSession */
        BaseUserSession: {
            /** Chain */
            chain: string;
            status: components["schemas"]["SessionState"];
            /** Positioninwaitlist */
            positionInWaitList?: number | null;
            classData: components["schemas"]["SessionRezervoClass"];
        };
        /** Body_upsert_user_avatar_user_me_avatar_put */
        Body_upsert_user_avatar_user_me_avatar_put: {
            /** File */
            file: string;
        };
        /** BookingCancellationPayload */
        BookingCancellationPayload: {
            /** Classid */
            classId: string;
        };
        /** BookingPayload */
        BookingPayload: {
            /** Classid */
            classId: string;
        };
        BranchIdentifier: string;
        /** BranchProfile */
        BranchProfile: {
            identifier: components["schemas"]["BranchIdentifier"];
            /** Name */
            name: string;
            /** Locations */
            locations: components["schemas"]["BaseLocation"][];
        };
        /** ChainConfig */
        ChainConfig: {
            /** Recurringbookings */
            recurringBookings: components["schemas"]["Class"][];
            /**
             * Active
             * @default true
             */
            active: boolean;
            /** Chain */
            chain: string;
        };
        /** ChainProfile */
        ChainProfile: {
            /** Identifier */
            identifier: string;
            /** Name */
            name: string;
            images: components["schemas"]["ChainProfileImages"];
        };
        /** ChainProfileImages */
        ChainProfileImages: {
            light: components["schemas"]["ThemeSpecificImages"];
            dark: components["schemas"]["ThemeSpecificImages"];
            common: components["schemas"]["ThemeAgnosticImages"];
        };
        /** ChainResponse */
        ChainResponse: {
            profile: components["schemas"]["ChainProfile"];
            /** Branches */
            branches: components["schemas"]["BranchProfile"][];
        };
        /** ChainUserCredentials */
        ChainUserCredentials: {
            /** Username */
            username: string;
            /** Password */
            password?: string | null;
        };
        /** ChainUserProfile */
        ChainUserProfile: {
            /** Username */
            username: string;
            /** Isauthverified */
            isAuthVerified: boolean;
        };
        /** ChainUserTOTPPayload */
        ChainUserTOTPPayload: {
            /** Totp */
            totp: string;
        };
        /** CheckInPayload */
        CheckInPayload: {
            /** Terminalid */
            terminalId: string;
            /** Printticket */
            printTicket: boolean;
        };
        /** CheckInTerminal */
        CheckInTerminal: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            /** Hasprinter */
            hasPrinter: boolean;
        };
        /** Class */
        Class: {
            /** Activityid */
            activityId: string;
            /** Weekday */
            weekday: number;
            /** Locationid */
            locationId: string;
            startTime: components["schemas"]["ClassTime"];
            /** Displayname */
            displayName?: string | null;
        };
        /** ClassTime */
        ClassTime: {
            /** Hour */
            hour: number;
            /** Minute */
            minute: number;
        };
        /** Community */
        Community: {
            /** Users */
            users: components["schemas"]["CommunityUser"][];
        };
        /** CommunityUser */
        CommunityUser: {
            /**
             * Userid
             * Format: uuid
             */
            userId: string;
            /** Name */
            name: string;
            /** Chains */
            chains: string[];
            relationship: components["schemas"]["UserRelationship"];
        };
        /** Features */
        Features: {
            /** Slackconnected */
            slackConnected: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HourAndMinute */
        HourAndMinute: {
            /** Hour */
            hour: number;
            /** Minute */
            minute: number;
        };
        /** InitiatedTOTPFlowResponse */
        InitiatedTOTPFlowResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "initiated_totp_flow";
            /** Totpregex */
            totpRegex?: string | null;
        };
        LocationIdentifier: string;
        /** Notifications */
        Notifications: {
            /**
             * Reminderslack
             * @default false
             */
            reminderSlack: boolean;
            /** Reminderhoursbefore */
            reminderHoursBefore?: number | null;
            reminderAllowedTimeWindow?: components["schemas"]["AllowedTimeWindowConfig"] | null;
        };
        /** PushNotificationGrants */
        PushNotificationGrants: {
            /**
             * Booking
             * @default false
             */
            booking: boolean;
            /**
             * Community
             * @default false
             */
            community: boolean;
            /**
             * Reminder
             * @default false
             */
            reminder: boolean;
        };
        /** PushNotificationSubscription */
        PushNotificationSubscription: {
            /** Endpoint */
            endpoint: string;
            keys: components["schemas"]["PushNotificationSubscriptionKeys"];
            grants?: components["schemas"]["PushNotificationGrants"];
        };
        /** PushNotificationSubscriptionKeys */
        PushNotificationSubscriptionKeys: {
            /** P256Dh */
            p256dh: string;
            /** Auth */
            auth: string;
        };
        /** RezervoActivity */
        RezervoActivity: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Description */
            description?: string | null;
            /** Additionalinformation */
            additionalInformation?: string | null;
            /** Color */
            color: string;
            /** Image */
            image?: string | null;
        };
        /** RezervoBaseCategory */
        RezervoBaseCategory: {
            /** Name */
            name: string;
            /** Color */
            color: string;
        };
        /** RezervoClass */
        RezervoClass: {
            /** Id */
            id: string;
            /**
             * Starttime
             * Format: date-time
             */
            startTime: string;
            /**
             * Endtime
             * Format: date-time
             */
            endTime: string;
            location: components["schemas"]["RezervoLocation"];
            activity: components["schemas"]["RezervoActivity"];
            /** Instructors */
            instructors: components["schemas"]["RezervoInstructor"][];
            /** Isbookable */
            isBookable: boolean;
            /** Iscancelled */
            isCancelled: boolean;
            /** Canceltext */
            cancelText?: string | null;
            /** Totalslots */
            totalSlots?: number | null;
            /** Availableslots */
            availableSlots?: number | null;
            /** Waitinglistcount */
            waitingListCount?: number | null;
            /** Userstatus */
            userStatus?: string | null;
            /**
             * Bookingopensat
             * Format: date-time
             */
            bookingOpensAt: string;
        };
        /** RezervoDay */
        RezervoDay: {
            /** Dayname */
            dayName: string;
            /** Date */
            date: string;
            /** Classes */
            classes: components["schemas"]["RezervoClass"][];
        };
        /** RezervoInstructor */
        RezervoInstructor: {
            /** Name */
            name: string;
        };
        /** RezervoLocation */
        RezervoLocation: {
            /** Id */
            id: string;
            /** Studio */
            studio: string;
            /** Room */
            room?: string | null;
        };
        /** RezervoSchedule */
        RezervoSchedule: {
            /** Days */
            days: components["schemas"]["RezervoDay"][];
        };
        /** RootModel[Annotated[Union[UpdatedChainUserCredsResponse, InitiatedTOTPFlowResponse], FieldInfo(annotation=NoneType, required=True, discriminator='status')]] */
        RootModel_Annotated_Union_UpdatedChainUserCredsResponse__InitiatedTOTPFlowResponse___FieldInfo_annotation_NoneType__required_True__discriminator__status____: components["schemas"]["UpdatedChainUserCredsResponse"] | components["schemas"]["InitiatedTOTPFlowResponse"];
        /** SessionRezervoClass */
        SessionRezervoClass: {
            /** Id */
            id: string;
            /**
             * Starttime
             * Format: date-time
             */
            startTime: string;
            /**
             * Endtime
             * Format: date-time
             */
            endTime: string;
            location: components["schemas"]["RezervoLocation"];
            activity: components["schemas"]["RezervoActivity"];
            /** Instructors */
            instructors: components["schemas"]["RezervoInstructor"][];
        };
        /**
         * SessionState
         * @enum {string}
         */
        SessionState: "CONFIRMED" | "BOOKED" | "WAITLIST" | "PLANNED" | "NOSHOW" | "UNKNOWN";
        /** ThemeAgnosticImages */
        ThemeAgnosticImages: {
            /** Smalllogo */
            smallLogo: string;
        };
        /** ThemeSpecificImages */
        ThemeSpecificImages: {
            /** Largelogo */
            largeLogo: string;
        };
        /** UpdatedChainUserCredsResponse */
        UpdatedChainUserCredsResponse: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "updated";
            profile: components["schemas"]["ChainUserProfile"];
        };
        /** UpsertUserResponse */
        UpsertUserResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
        };
        /** UserIdAndNameWithIsSelf */
        UserIdAndNameWithIsSelf: {
            /** Isself */
            isSelf: boolean;
            /**
             * Userid
             * Format: uuid
             */
            userId: string;
            /** Username */
            userName: string;
        };
        /** UserLifecycleEvent */
        UserLifecycleEvent: {
            user: components["schemas"]["UserLifecycleEventUser"];
            /** Type */
            type: string;
        };
        /** UserLifecycleEventUser */
        UserLifecycleEventUser: {
            /** Id */
            id: string;
            /** Username */
            username: string;
        };
        /** UserLifecyclePayload */
        UserLifecyclePayload: {
            event: components["schemas"]["UserLifecycleEvent"];
        };
        /** UserNameSessionStatus */
        UserNameSessionStatus: {
            /** Isself */
            isSelf: boolean;
            /**
             * Userid
             * Format: uuid
             */
            userId: string;
            /** Username */
            userName: string;
            status: components["schemas"]["SessionState"];
            /** Positioninwaitlist */
            positionInWaitList?: number | null;
        };
        /** UserPreferences */
        UserPreferences: {
            notifications?: components["schemas"]["Notifications"] | null;
        };
        /**
         * UserRelationship
         * @enum {string}
         */
        UserRelationship: "UNKNOWN" | "REQUEST_SENT" | "REQUEST_RECEIVED" | "FRIEND";
        /**
         * UserRelationshipAction
         * @enum {string}
         */
        UserRelationshipAction: "ADD_FRIEND" | "ACCEPT_FRIEND" | "DENY_FRIEND" | "REMOVE_FRIEND";
        /** UserRelationshipActionPayload */
        UserRelationshipActionPayload: {
            /**
             * Userid
             * Format: uuid
             */
            userId: string;
            action: components["schemas"]["UserRelationshipAction"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_chains_chains_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainResponse"][];
                };
            };
        };
    };
    get_chain_by_identifier_chains__chain_identifier__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chain_week_schedule_schedule__chain_identifier___compact_iso_week__get: {
        parameters: {
            query?: {
                location?: components["schemas"]["LocationIdentifier"][] | null;
            };
            header?: never;
            path: {
                chain_identifier: string;
                compact_iso_week: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RezervoSchedule"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chain_class_by_id_classes__chain_identifier___class_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
                class_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RezervoClass"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_activity_categories_categories_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RezervoBaseCategory"][];
                };
            };
        };
    };
    get_chain_user_profile__chain_identifier__user_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChainUserProfile"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_chain_user_creds__chain_identifier__user_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChainUserCredentials"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RootModel_Annotated_Union_UpdatedChainUserCredsResponse__InitiatedTOTPFlowResponse___FieldInfo_annotation_NoneType__required_True__discriminator__status____"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_chain_user__chain_identifier__user_delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_chain_user_totp__chain_identifier__user_totp_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChainUserTOTPPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_chain_config__chain_identifier__config_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseChainConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_chain_config__chain_identifier__config_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BaseChainConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseChainConfig"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_all_configs_index__chain_identifier__all_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["UserIdAndNameWithIsSelf"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_preferences_preferences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
        };
    };
    upsert_user_preferences_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserPreferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPreferences"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_features_features_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Features"];
                };
            };
        };
    };
    book_class_api__chain_identifier__book_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_booking_api__chain_identifier__cancel_booking_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BookingCancellationPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_sessions_index__chain_identifier__sessions_index_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["UserNameSessionStatus"][];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calendar_token_cal_token_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    get_calendar_cal_get: {
        parameters: {
            query: {
                token: string;
                include_past?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_push_notifications_public_key_notifications_push_public_key_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    subscribe_to_push_notifications_notifications_push_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushNotificationSubscription"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushNotificationSubscription"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_from_push_notifications_notifications_push_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushNotificationSubscription"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_push_notifications_subscription_notifications_push_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PushNotificationSubscription"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PushNotificationGrants"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    slack_action_slackinteraction_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    upsert_user_user_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UpsertUserResponse"];
                };
            };
        };
    };
    get_user_sessions_user_sessions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseUserSession"][];
                };
            };
        };
    };
    get_user_chain_configs_user_chain_configs_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["ChainConfig"];
                    };
                };
            };
        };
    };
    get_user_avatar_user_me_avatar__size_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                size_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_avatar_by_id_user__user_id__avatar__size_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
                size_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_user_avatar_user_me_avatar_put: {
        parameters: {
            query?: never;
            header?: {
                "content-length"?: number | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upsert_user_avatar_user_me_avatar_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_avatar_user_me_avatar_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_community_community_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Community"];
                };
            };
        };
    };
    update_relationship_community_relationship_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRelationshipActionPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRelationship"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    user_lifecycle_webhooks_user_lifecycle_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserLifecyclePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    check_in__chain_identifier__check_in_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                chain_identifier: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CheckInPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
