/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ChainRouteImport } from './routes/$chain'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthTokenRouteImport } from './routes/api/auth/token'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainRoute = ChainRouteImport.update({
  id: '/$chain',
  path: '/$chain',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthTokenRoute = ApiAuthTokenRouteImport.update({
  id: '/api/auth/token',
  path: '/api/auth/token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$chain': typeof ChainRoute
  '/login': typeof LoginRoute
  '/api/auth/token': typeof ApiAuthTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$chain': typeof ChainRoute
  '/login': typeof LoginRoute
  '/api/auth/token': typeof ApiAuthTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$chain': typeof ChainRoute
  '/login': typeof LoginRoute
  '/api/auth/token': typeof ApiAuthTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$chain' | '/login' | '/api/auth/token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$chain' | '/login' | '/api/auth/token'
  id: '__root__' | '/' | '/$chain' | '/login' | '/api/auth/token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChainRoute: typeof ChainRoute
  LoginRoute: typeof LoginRoute
  ApiAuthTokenRoute: typeof ApiAuthTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$chain': {
      id: '/$chain'
      path: '/$chain'
      fullPath: '/$chain'
      preLoaderRoute: typeof ChainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/token': {
      id: '/api/auth/token'
      path: '/api/auth/token'
      fullPath: '/api/auth/token'
      preLoaderRoute: typeof ApiAuthTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChainRoute: ChainRoute,
  LoginRoute: LoginRoute,
  ApiAuthTokenRoute: ApiAuthTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
