name: CI
on:
    pull_request:
    push:
        branches: [main]

    workflow_dispatch:

jobs:
    code_style:
        name: Prettier Check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 10
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Prettier Check
              run: pnpm run prettier:check

    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 9
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Lint
              run: pnpm run lint

    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 9
            - uses: actions/setup-node@v4
              with:
                  node-version: "22"
                  cache: pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Build
              run: pnpm build
